- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_attributes_table_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
- metanorma-plugin-lutaml.gemspec
- spec/metanorma/plugin/lutaml/lutaml2_text_preprocessor_spec.rb
Support for expressir hyperlink formatter, lutaml version bump, use new Lutaml::Parser format
> (Feature) expressir hyperlink support, use new Lutaml::Parser format

- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml_datamodel_attributes_table_preprocessor_spec.rb
https://github.com/metanorma/metanorma-plugin-lutaml/issues/20 small fixes, use the correct cardinality
> (Hotfix) cardinality specs

- Makefile
- lib/metanorma/plugin/lutaml/liquid/custom_filters.rb
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_attributes_table_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
- metanorma-plugin-lutaml.gemspec
- spec/metanorma/plugin/lutaml/lutaml2_text_preprocessor_spec.rb
Support for liquid `include` statements - lutaml macro
> (Feature) liquid includes

- metanorma-plugin-lutaml.gemspec
> #30 test macos ruby 3.0.0

- README.adoc
- lib/metanorma/plugin/lutaml/liquid_templates/_diagrams_block.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages.liquid
https://github.com/metanorma/metanorma-plugin-lutaml/issues/42
> Support for `format` attribute - lutaml_uml_datamodel_description, .diagram_include_block macro

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml2_text_preprocessor_spec.rb
> Rename [lutaml] to [lutaml_express]

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list.liquid
- spec/fixtures/datamodel_description_sections.xml
- spec/fixtures/datamodel_description_sections_render_style_data_dictionary.xml
- spec/fixtures/datamodel_description_sections_render_style_entity_list.xml
- spec/fixtures/datamodel_description_sections_render_style_random.xml
- spec/fixtures/datamodel_description_sections_section_depth.xml
- spec/fixtures/datamodel_description_sections_tree.xml
- spec/fixtures/temporary_datamodel_description_config.yml
https://github.com/metanorma/ogc-citygml-xmi/issues/60
> the proper Union and DataType display

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml2_text_preprocessor_spec.rb
https://github.com/metanorma/metanorma-plugin-lutaml/issues/53
> Support for lutaml macro

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_data_dictionary.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_data_dictionary_class.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list.liquid
- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
https://github.com/metanorma/metanorma-plugin-lutaml/issues/70 support for ref overwrite using yaml options file - lutaml_uml_datamodel_description
> Ref overwrite using options file - lutaml_uml_datamodel_description

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_data_dictionary.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_data_dictionary_class.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list_class.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list_classes.liquid
- spec/fixtures/datamodel_description_sections_nested_macroses.xml
- spec/fixtures/datamodel_description_sections_render_style_data_dictionary.xml
- spec/fixtures/datamodel_description_sections_render_style_entity_list.xml
- spec/fixtures/datamodel_description_sections_skip_tables.xml
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
https://github.com/metanorma/ogc-citygml-xmi/issues/124
> Fix sections naming, missing refs

- lib/metanorma-plugin-lutaml.rb
- lib/metanorma/plugin/lutaml/liquid_templates/_packages_entity_list.liquid
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_table_inline_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_attributes_table_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_class_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
- metanorma-plugin-lutaml.gemspec
- spec/fixtures/datamodel_description_sections.xml
- spec/fixtures/datamodel_description_sections_nested_macroses.xml
- spec/fixtures/datamodel_description_sections_package_entities.xml
- spec/fixtures/datamodel_description_sections_render_style_data_dictionary.xml
- spec/fixtures/datamodel_description_sections_render_style_entity_list.xml
- spec/fixtures/datamodel_description_sections_render_style_liquid_interpolate_data_dictionary.xml
- spec/fixtures/datamodel_description_sections_render_style_liquid_interpolate_entity_list.xml
- spec/fixtures/datamodel_description_sections_render_style_liquid_interpolate_random.xml
- spec/fixtures/datamodel_description_sections_render_style_random.xml
- spec/fixtures/datamodel_description_sections_section_depth.xml
- spec/fixtures/datamodel_description_sections_skip_tables.xml
- spec/fixtures/datamodel_description_sections_tree.xml
- spec/metanorma/plugin/lutaml/lutaml2_text_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_datamodel_attributes_table_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_diagram_block_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_figure_inline_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_table_inline_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
- spec/spec_helper.rb
> Add `lutaml_uml_class` command

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_uml_class_preprocessor.rb
- lib/metanorma/plugin/lutaml/version.rb
> Add `depth` config to lutaml_uml_class command

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
> feat: change config yaml structure `schema` to Hash

- lib/metanorma/plugin/lutaml/express_remarks_decorator.rb
- lib/metanorma/plugin/lutaml/liquid/custom_filters.rb
- lib/metanorma/plugin/lutaml/liquid/multiply_local_file_system.rb
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_attributes_table_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_class_preprocessor.rb
- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
- metanorma-plugin-lutaml.gemspec
- spec/fixtures/lutaml/datamodel_description_sections_nested_macroses.xml
- spec/fixtures/lutaml/datamodel_description_sections_render_style_liquid_interpolate_random.xml
- spec/metanorma/plugin/lutaml/lutaml_diagram_block_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_table_inline_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/utils_spec.rb
- spec/spec_helper.rb
But all relevant specs are failing. All we use is `Coradoc::ReverseAdoc.convert`
> feat: (WIP) use coradoc

- lib/metanorma/plugin/lutaml/liquid_templates/_packages.liquid
- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
> Load ea mdg extension

- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
> Add option to render nested packages

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_class.liquid
> Avoid same anchor ids for different types of models

- lib/metanorma/plugin/lutaml/lutaml_gml_dictionary_base.rb
- metanorma-plugin-lutaml.gemspec
> Update gem ogc-gml

- lib/metanorma/plugin/lutaml/lutaml_gml_dictionary_base.rb
> Fix uninitialized constant Metanorma::Ogc::Gml (NameError)

- lib/metanorma/plugin/lutaml/lutaml_gml_dictionary_block_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
> Change logger to use Metanorma::Util.log

- lib/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
- spec/support/shared_examples_for_lutaml_uml_datamodel_description_preprocessor.rb
> Update specs to fix performance issue

- Gemfile
- lib/metanorma-plugin-lutaml.rb
- lib/metanorma/plugin/lutaml/liquid_drops/klass_table_attribute_drop.rb
- lib/metanorma/plugin/lutaml/liquid_drops/klass_table_content_drop.rb
- lib/metanorma/plugin/lutaml/liquid_drops/klass_table_drop.rb
- lib/metanorma/plugin/lutaml/liquid_drops/klass_table_general_drop.rb
- lib/metanorma/plugin/lutaml/liquid_templates/_klass_assoc_row.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_klass_row.liquid
- lib/metanorma/plugin/lutaml/liquid_templates/_klass_table.liquid
- lib/metanorma/plugin/lutaml/lutaml_klass_table_block_macro.rb
- spec/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_klass_table_block_macro_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples_for_lutaml_uml_datamodel_description_preprocessor.rb
> Macro klass table

- README.adoc
- lib/metanorma/plugin/lutaml/liquid_templates/_klass_table.liquid
- lib/metanorma/plugin/lutaml/lutaml_klass_table_block_macro.rb
- spec/fixtures/lutaml/liquid_templates/_klass_assoc_row.liquid
- spec/fixtures/lutaml/liquid_templates/_klass_row.liquid
- spec/fixtures/lutaml/liquid_templates/_klass_table.liquid
- spec/metanorma/plugin/lutaml/lutaml_ea_xmi_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_klass_table_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
- spec/support/shared_examples_for_lutaml_uml_datamodel_description_preprocessor.rb
> User defined templates for lutaml_klass_table

- README.adoc
> Add documentation for lutaml_ea_xmi

- lib/metanorma/plugin/lutaml/liquid_templates/_klass_table.liquid
- spec/fixtures/lutaml/liquid_templates/_klass_table.liquid
> Update liquid templates

- spec/spec_helper.rb
> Some specs failed due to missing the line <flavor>standoc</flavor>

- README.adoc
> Update README of lutaml_klass_table and lutaml_ea_xmi for guidance

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_klass_table_block_macro.rb
- spec/metanorma/plugin/lutaml/lutaml_klass_table_block_macro_spec.rb
> Enhanced filtering options for lutaml_klass_table

- metanorma-plugin-lutaml.gemspec
> Update the version of expressir

- README.adoc
- lib/metanorma/plugin/lutaml/liquid_templates/_klass_table.liquid
- lib/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_ea_xmi_base.rb
- spec/fixtures/lutaml/lutaml_xmi_index_config.yml
- spec/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_xmi_index_spec.rb
> Add lutaml-xmi-index to support multiple xmi files

- lib/metanorma/plugin/lutaml/utils.rb
> Fix deprecation warning from Liquid v5.6.x

- README.adoc
> Fix README

- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
> Fix Liquid error: This liquid context does not allow includes

- Gemfile
> Update gem metanorma-standoc

- lib/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_ea_xmi_base.rb
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- lib/metanorma/plugin/lutaml/utils.rb
> Remove DocumentWrapper

- lib/metanorma/plugin/lutaml/lutaml_ea_xmi_base.rb
> Resolve paths of ea extensions based on the location of config yaml file

- README.adoc
> Add documentation to explain ea_extension in the config yaml file

- lib/metanorma-plugin-lutaml.rb
- lib/metanorma/plugin/lutaml/config.rb
- lib/metanorma/plugin/lutaml/config/guidance.rb
- lib/metanorma/plugin/lutaml/config/guidance_attribute.rb
- lib/metanorma/plugin/lutaml/config/guidance_klass.rb
- lib/metanorma/plugin/lutaml/config/package.rb
- lib/metanorma/plugin/lutaml/config/root.rb
- lib/metanorma/plugin/lutaml/liquid/custom_filters.rb
- lib/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_ea_xmi_base.rb
- lib/metanorma/plugin/lutaml/lutaml_klass_table_block_macro.rb
- metanorma-plugin-lutaml.gemspec
- spec/fixtures/lutaml/lutaml_uml_datamodel_description_config_package_entities.yml
- spec/metanorma/plugin/lutaml/config/root_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
> Migrate YAML config files to use lutaml-model

- lib/metanorma/plugin/lutaml/express_remarks_decorator.rb
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
> Decorate all remarks

- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
> Expose context schemas_order for ordering of the schemas

- README.adoc
- lib/metanorma/plugin/lutaml/lutaml_preprocessor.rb
- spec/metanorma/plugin/lutaml/lutaml_express_preprocessor_spec.rb
> Get rid of the "selected" feature

- lib/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro.rb
- lib/metanorma/plugin/lutaml/lutaml_ea_xmi_base.rb
- lib/metanorma/plugin/lutaml/lutaml_klass_table_block_macro.rb
- spec/metanorma/plugin/lutaml/lutaml_ea_xmi_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_klass_table_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
- spec/support/shared_examples_for_lutaml_uml_datamodel_description_preprocessor.rb
> Refactor and generalize performance improvements

- spec/metanorma/plugin/lutaml/lutaml_klass_table_block_macro_spec.rb
- spec/support/shared_examples_for_lutaml_uml_datamodel_description_preprocessor.rb
> Fix failed specs in lutaml_klass_table_block_macro_spec.rb

- docs/usages/json_yaml.adoc
- lib/metanorma/plugin/lutaml/base_structured_text_preprocessor.rb
- lib/metanorma/plugin/lutaml/content.rb
- lib/metanorma/plugin/lutaml/parse_error.rb
- spec/fixtures/lutaml/datastruct/invalid.json
- spec/fixtures/lutaml/datastruct/invalid.yaml
- spec/metanorma/plugin/lutaml/lutaml_express_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/macros_data2text_spec.rb
- spec/metanorma/plugin/lutaml/macros_yaml2text_spec.rb
- spec/support/shared_examples/structured_data_2_text_preprocessor.rb
> Validate file loading

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_class.liquid
- spec/assets/codes_table.html
- spec/metanorma/plugin/lutaml/lutaml_diagram_block_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_ea_diagram_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_express_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/macros_data2text_spec.rb
- spec/metanorma/plugin/lutaml/macros_yaml2text_spec.rb
- spec/support/shared_examples/lutaml_uml_datamodel_description_preprocessor.rb
- spec/support/shared_examples/structured_data_2_text_preprocessor.rb
> Update default template of package class

- lib/metanorma/plugin/lutaml/liquid/custom_filters/file_exist.rb
- lib/metanorma/plugin/lutaml/utils.rb
> Create a liquid filter to check the existence of a file

- lib/metanorma/plugin/lutaml/liquid_templates/_packages_class.liquid
- metanorma-plugin-lutaml.gemspec
- spec/metanorma/plugin/lutaml/lutaml_ea_xmi_preprocessor_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_uml_datamodel_description_preprocessor_spec.rb
> Update default package class template

- docs/usages/enterprise_architect.adoc
> Update doc ea config

- docs/usages/enterprise_architect.adoc
- lib/metanorma-plugin-lutaml.rb
- lib/metanorma/plugin/lutaml/liquid_templates/_enum_table.liquid
- lib/metanorma/plugin/lutaml/lutaml_enum_table_block_macro.rb
- spec/fixtures/lutaml/liquid_templates/_enum_table.liquid
- spec/metanorma/plugin/lutaml/lutaml_enum_table_block_macro_spec.rb
- spec/metanorma/plugin/lutaml/lutaml_text_preprocessor_spec.rb
- spec/spec_helper.rb
> Add macro lutaml enum table
